### ISSUE TITLE
Ошибка расчета по всем тикерам

### ISSUE THREAD

**Issue by slavb18** [bystrobank/stockvaluation#9]
2023-02-14 06:35:48 +03:00:   File "fairpricecalc/__main__.py", line 34, in main                                                                                       
2023-02-14 06:35:48 +03:00:     result = calculator.calculate(date)                                                                                                    
2023-02-14 06:35:48 +03:00:   File "fairpricecalc/fair_price_calculator.py", line 23, in calculate                                                                     
2023-02-14 06:35:48 +03:00:     initial_volume, isin, market_data = provider.get_exchange_data()                                                                       
2023-02-14 06:35:48 +03:00:   File "fairpricecalc/exchange_data_provider.py", line 25, in get_exchange_data                                                            
2023-02-14 06:35:48 +03:00:     exchange_df = parser.parse_exchange_files(exchange_files)                                                                              
2023-02-14 06:35:48 +03:00:   File "fairpricecalc/dataframe_parser.py", line 28, in parse_exchange_files                                                               
2023-02-14 06:35:48 +03:00:     raise NameError('Data for this ticker does not exist: ' + self.ticker)                                                                 
2023-02-14 06:35:48 +03:00: NameError: Data for this ticker does not exist:  ГПБ БО-19                                                                                 
2023-02-14 06:35:48 +03:00:                                                                                                                                            
2023-02-14 06:35:48 +03:00:     at StockValuationService.valuate (/home/cloudtreasury/.next/server/chunks/370.js:158:19)                                               
2023-02-14 06:35:48 +03:00:     at CalculateFairPrice.process (/home/cloudtreasury/.next/server/pages/api/fairprice/calculations.js:151:60)                            
2023-02-14 06:35:48 +03:00:     at processUsecaseApiInstance (/home/cloudtreasury/.next/server/chunks/370.js:400:26)                                                   
2023-02-14 06:35:48 +03:00:     at Array.<anonymous> (/home/cloudtreasury/.next/server/pages/api/fairprice/calculations.js:130:111)                                    
2023-02-14 06:35:48 +03:00:     at runMicrotasks (<anonymous>)                                                                                                         
2023-02-14 06:35:48 +03:00:     at processTicksAndRejections (internal/process/task_queues.js:95:5)                                                                    
2023-02-15 06:32:24 +03:00: Error: Traceback (most recent call last):

**Comment by slavb18** [comment]
на сервере кончилось место
